### ISSUE TITLE
[Bug] When "Separate Left/Right Cross Hotbars" is set to > 0, Hotbar Help text for the right side is not aligned correctly

### ISSUE THREAD

**Issue by ryankhart** [ItsBexy/CrossUp#10]
![image](https://user-images.githubusercontent.com/3673962/168600383-d37ee91e-621c-4d29-877c-8b963a745169.png)

**Comment by ItsBexy** [comment]
Hm, I'm having trouble replicating this one. Technically whenever the right side is selected, the whole bar is "sliding over" that way, carrying the hotbar help the appropriate distance, so it's very strange that it would end up in the middle like that. I'll take a closer look and see if I can figure out what exactly is happening here.

**Comment by ryankhart** [comment]
I can't reproduce it either anymore after the update to 0.2.0.0.

I'll close this for now unless I manage to trigger the bug again.
