### ISSUE TITLE
[Suggestion] Option to "Always Display Expanded XHB"

### ISSUE THREAD

**Issue by thedaryen** [ItsBexy/CrossUp#12]
Thank you so much for this plugin! I've been waiting for something like this for a long time.

So, the suggestion: I always wanted an option within the game to be able to always display the Expanded XHB (the way we can do with the Double XHB) so I can track the cooldowns on there without using KB hotbars. Even better if you could choose to only always display the left one, the right one or both.

Also, it'd be cool if we could set it so that highlighting the Expanded XHB doesn't hide the main XHB, for the same reason (if for example you have AOEs on Expanded but don't want to lose visibility of the cooldowns on your main XHB while AOEing).

**Comment by ItsBexy** [comment]
Hi, I'm happy to hear you like the plugin, thank you!

Just to clarify-- the plugin already has a feature to display the Expanded Hold Cross Hotbars separately, keep them continuously visible, and also keep the main XHB visible while using them. It's designed to look and function as similarly as possible to the in-game setting that already exists for the WXHB.

![501a9140b613e30e64a0ff673179187d](https://user-images.githubusercontent.com/103910869/169387629-e6c9bd17-4973-4b12-98ec-58ecfd4bf29b.png)

I do plan to add the feature to only display a single Expanded Hold bar (ie, for players who prefer to set both inputs to the same thing). Was there other functionality you were looking for? Or was this feature not working properly for you? (I'm eager to bugfix if so)
