### ISSUE TITLE
After fresh launch of FFXIV, `Separate EXHB` bars still in rows instead of in cross layout

### ISSUE THREAD

**Issue by ryankhart** [ItsBexy/CrossUp#13]
This bug does not reproduce itself after an uninstall and reinstall of the plugin. And when I go into the /xup settings, disabling and re-enabling "Display Expanded Hold Controls Separately" does fix this particular issue for the remaining time that I am logged into my character.

I wonder if that means that adding a delay for the plugin to initialize upon first login would help that issue?

**Comment by ItsBexy** [comment]
I did already put in a fix for this that does something similar to what you suggest-- when the player logs in and the hotbar nodes first appear (which happens midway through the loading screen), the plugin will run the arrangement function repeatedly for the next five seconds to ensure they're "primed" and end up in the right place.

But this solution might be affected by load times (for a longer load time on login, that five second span might not be enough). If so, I'll see about finding another property in ClientStructs that I can tie initialization to.

At any rate, if it's the same issue I was dealing with before, it shouldn't be necessary to go into the plugin settings-- a tap of a trigger should be enough to nudge the bars into the proper alignment.

**Comment by ryankhart** [comment]
Oh, I wonder if it's because I use Penumbra to load in about 100 GB worth of installed 3rd party textures. That could be increasing load times beyond what your code expects to have to wait for. The next time I get the chance, I'll try disabling 3rd party textures and login to see if that works around this issue I'm having.

**Comment by ryankhart** [comment]
Sorry for keeping you waiting on this.

~~I finally narrowed down what appears to be the cause of my issue. I have my separate EXHB set to hotbars 5 and 6 because, at the time of installing CrossUp, I had already been using 7, 8, 9, and 10 for other uses and didn't want to swap all those actions to another hotbar.~~

~~When I switched my separate EXHB from 5 and 6 to 9 and 10, like it was by default, it fixed the issue where the separate EXHBs were being shown in rows instead of the + layouts.~~

For this test, ~~in which I was able to workaround the issue,~~ I had also removed all other plugins except for CrossUp, and I had also  tested my vanilla FFXIV settings with 100% UI scaling rather than the 300% that I play on as well as setting all the individual HUD elements to 100% as opposed to the usual 80% that I usually have most things on. None of these changes had any impact on this particular issue for me.

**Comment by ryankhart** [comment]
Actually...it's just hotbar 9 that is correctly showing up in cross hotbar layout, but hotbar 10 is still in rows. I just didn't notice it in my testing earlier because my hotbar 10 isn't filled in all the way, and I have my separate XHB directly up from my main XHBs.

I even tested by putting an action in every single EXHB slot, disabling the "Display Expanded Hold Controls Separately" feature, fully emptying my entire hotbars 9 and 10 so that they are both the same, empty, re-enabled the feature in CrossUp, logged out, and back in again, and it still only works for the right side of the EXHB (hotbar 10) and not the left (hotbar 9).

**Comment by ryankhart** [comment]
Okay, NOW I understand what's going on. The reason why hotbar 9 was working for me and not hotbars 5, 6, and 10 were not working for me on login were because hotbar 9 was the only hotbar I had tried where it's layout was in 12x1 layout. All the other hotbars, I had in 4x3 layout. As soon as I switched each of the hotbars that I was using for the Expanded Hold Controls to the 12x1 layout, when I logged in, it correctly displayed those hotbars as cross hotbars as expected.

**Comment by ItsBexy** [comment]
Taking another step to try and handle this problem in 0.3.0.2, I've once again moved the plugin's initialization process to wait until after the player has logged in AND the hotbar nodes exist AND the nodes are in place AND the player's job ID can be determined. 

That should hopefully be late enough that the post-login "nudge" function to correct the bars will work, irrespective of load times.
