### ISSUE TITLE
{Bug} "Button Glow" and "Button Pulse" do not apply to WXHB button presses

### ISSUE THREAD

**Issue by Otaku-2** [ItsBexy/CrossUp#18]
![image](https://user-images.githubusercontent.com/21027484/171977122-d2311c65-9223-489b-8055-36ad86fa40d9.png)
![image](https://user-images.githubusercontent.com/21027484/171977130-30ea47af-d7ff-41a5-a323-bb7d152c7521.png)

**Comment by ItsBexy** [comment]
Fixed in 0.3.1.0. Thanks for the heads-up!
