### ISSUE TITLE
Negative Left/RIght Separation

### ISSUE THREAD

**Issue by figotech** [ItsBexy/CrossUp#19]
First of all: YOUR PLUGIN IS AMAZING. I have been waiting for an X-bar mod for ages.
THere is only one thing for it to be perfect:
Negative separation of Left and Right bars.... or essentially, I want the Left, right and the expanded ones to show exactly in the same place (I play with the bar hidden so for me it will only show when I press the trigger the  L or R.  This will probably need the option to hide the divider bar between L and R too.

THank you so much!

**Comment by ItsBexy** [comment]
This has been implemented in 0.4.2.0. If you set the separation value to -142, the Left/Right bars will now appear exactly on top of each other.

**Comment by figotech** [comment]
Thank you so much. Not gonna lie, ever since I posted I actually downloaded yoru code and made the mods to acheive this.. but it was messy, the centering code was moving stuff around  but i was able to get it working.. but any time we had an update i had to also re doqnload etc...  It was fun but defnitely this plugin dev is tough. You guys are the true heroes of light.
