### ISSUE TITLE
Duty Action UI element gets a black background in Diadem

### ISSUE THREAD

**Issue by tommadness** [ItsBexy/CrossUp#25]
When one bar of Compressed Aether is filled in Diadem, the background of the "Duty Action" UI element fills in black
![image](https://user-images.githubusercontent.com/15738031/235328219-d54165ad-a70e-4bb6-b07e-56980b846dad.png)

Message me on Discord (Tommadness in the XIVLauncher/Dalamud Discord) for a copy of the user's plugin config if needed.

**Comment by ItsBexy** [comment]
Interesting, thanks for the heads-up. I've only tested that UI element in Bozja and Island Sanctuary, so this is a good reminder to poke into other instances it appears. I'll see if I can figure out what's going on in Diadem.

**Comment by ItsBexy** [comment]
I haven't been able to reproduce the issue. The icon border in the screenshot leads me to think that this may be either:
-Solely a texture mod issue
-An interaction between CrossUp and a texture mod

I'd be happy to fix up any errors on my end that clash with other mods/plugins, but I'm at a bit of a dead end here. I think I'll have to close this one for now, unless I can get some information that helps me reproduce it.
