### ISSUE TITLE
Expanded Hold Controls UI doesn't display after entering and exiting /hudlayout

### ISSUE THREAD

**Issue by ryankhart** [ItsBexy/CrossUp#9]
Expanded Hold Controls UI doesn't display after entering and exiting /hudlayout

I need to open up the CrossUp settings and disable and re-enable "Display Expanded Hold Controls Separately" in order for it to show up.

### Expected behavior
Expanded Hold Controls UI should persist after /hudlayout has been exited if "Display Expanded Hold Controls Separately" option is enabled.

**Comment by ItsBexy** [comment]
Just to clarify, is the checkbox unchecking itself after using /hudlayout? Or does it remain checked, but not displaying the accompanying options?

**Comment by ryankhart** [comment]
I can't seem to reproduce this anymore after 0.2.0.0. Closing.
